USE [WorkoutHunter]
GO

/****** Object:  Table [dbo].[item]    Script Date: 2021/7/20 下午 12:04:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[item](
	[IID] [int] IDENTITY(1,1) NOT NULL,
	[ItemName] [nvarchar](20) NULL,
	[ItemInfo] [nvarchar](50) NULL,
	[ItemPic] [nvarchar](20) NULL,
	[Buff] [nchar](50) NULL,
<<<<<<< HEAD
=======
	[CostMoney] [int] NULL,
>>>>>>> bf41df21e5fe8c2912a7e03b6f831d48b0de92c2
 CONSTRAINT [PK_item] PRIMARY KEY CLUSTERED
(
	[IID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IN_Unique] UNIQUE NONCLUSTERED
(
	[ItemName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
