USE [WorkoutHunter]
GO

/****** Object:  Table [dbo].[monster]    Script Date: 2021/7/20 下午 12:05:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[monster](
	[MID] [int] IDENTITY(1,1) NOT NULL,
	[MonsterName] [nvarchar](10) NULL,
	[MonsterDamage] [int] NULL,
	[MonsterClass] [bit] NULL,
	[MonsterPic] [nvarchar](10) NULL,
 CONSTRAINT [PK_monster] PRIMARY KEY CLUSTERED
(
	[MID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [MN_Unique] UNIQUE NONCLUSTERED
(
	[MonsterName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


